### ISSUE TITLE
Allow secrets to be passed as a parameter for CPython 

### ISSUE THREAD

**Issue by FoamyGuy** [adafruit/Adafruit_Blinka_PyPortal#16]
I am working on trying out this library along with my PyGameDisplay running on a PC with CPython 3.8.5. 

I ran into a bit of trouble because this library is trying to import secrets here: https://github.com/adafruit/Adafruit_Blinka_PyPortal/blob/d9bfb3da598a2a0b6d5a6104418f5d66d2ee75b4/adafruit_pyportal.py#L42

But in my environment this seems to be trying to import the [built-in module secrets](https://docs.python.org/3.8/library/secrets.html) instead of my local file with a dictionary containing API tokens. 

I was able to comment out the lines importing secrets and then did get some successful tests working (ones that don't need tokens). So the rest of the functionality of this module appears to be working well in this environment. 

The cleanest solution that I could think of was allowing a `secrets` dictionary to be passed as a parameter in the constructor, and then only try to import secrets if that parameter was `None`. That way in environments like mine the user could import secrets in user code and then pass them into this PyPortal library to get used for any requests that need tokens. 

I can work on making these changes if this an acceptable solution, just wanted to put it out there first and see if maybe I've missed something and there is an easier way.

**Comment by makermelissa** [comment]
Fixed via #17
