### ISSUE TITLE
Text not appearing in examples when run on a FT232H

### ISSUE THREAD

**Issue by makermelissa** [adafruit/Adafruit_Blinka_PyPortal#9]
The following example runs fine and uses the same assets not working in PyPortal:
```
"""
This test will initialize the display using displayio and draw a solid green
background, a smaller purple rectangle, and some yellow text. All drawing is done
using the displayio module.

Pinouts are for the PiTFT and should be run in CPython.
"""
import board
import terminalio
import displayio
from adafruit_display_text import label
from adafruit_bitmap_font import bitmap_font
import adafruit_ili9341

# Release any resources currently in use for the displays
displayio.release_displays()

spi = board.SPI()
tft_cs = board.D4
tft_dc = board.D5

display_bus = displayio.FourWire(spi, command=tft_dc, chip_select=tft_cs, reset=board.D6)
display = adafruit_ili9341.ILI9341(display_bus, width=320, height=240)

# Make the display context
splash = displayio.Group(max_size=10)
display.show(splash)

# Draw a green background
color_bitmap = displayio.Bitmap(display.width, display.height, 1)
color_palette = displayio.Palette(1)
color_palette[0] = 0x00FF00  # Bright Green

bg_sprite = displayio.TileGrid(color_bitmap, pixel_shader=color_palette, x=0, y=0)

splash.append(bg_sprite)

# Draw a smaller inner rectangle
inner_bitmap = displayio.Bitmap(display.width - 40, display.height - 40, 1)
inner_palette = displayio.Palette(1)
inner_palette[0] = 0xAA0088  # Purple
inner_sprite = displayio.TileGrid(inner_bitmap, pixel_shader=inner_palette, x=20, y=20)
splash.append(inner_sprite)

my_bitmap = displayio.OnDiskBitmap(open("bitcoin_background.bmp", "rb"))
my_tilegrid = displayio.TileGrid(my_bitmap, pixel_shader=displayio.ColorConverter())
splash.append(my_tilegrid)

# Draw a label
text_group = displayio.Group(max_size=10, x=70, y=120)
font = bitmap_font.load_font("Arial-Bold-24-Complete.bdf")
text = "Hello World!"
text_area = label.Label(font, text=text, color=0x000000)
text_group.append(text_area)  # Subgroup for text scaling
splash.append(text_group)

while True:
    pass
```
I'm not sure if it's drawing stuff out of order or what. The same code that fails to work on the FT232H works fine on the Raspberry Pi.

**Comment by makermelissa** [comment]
Also, no errors occur. It's just silently not working.

**Comment by caternuson** [comment]
Can you provide more details of the hardware setup. What display is attached to the FT232H? What host is the FT232H attached to? Are you using the newer USB C FT232H breakout?

**Comment by makermelissa** [comment]
Sure, I have a 2.8" resistive TFT breakout, I'm using the older FT232H, though I have a newer one as well, and I'm using MacOS for the operating system, though I could try it out on Windows and Linux as well.

**Comment by caternuson** [comment]
The old breakout should be fine. And MacOS should also be OK. As a hardware sanity check, does it work with PIL like this example?
https://learn.adafruit.com/circuitpython-on-any-computer-with-ft232h/tft-display

**Comment by makermelissa** [comment]
Well, it's outputting the background just fine and the Blinka Displayio library uses PIL, so I'm fairly certain it's not hardware related. I think the issue exists in the Blinka PyPortal library here specifically, although now that I'm thinking about it, I do have a theory. I have the display refresh happening in a separate thread and I'm wondering if due to a race condition that it's getting the background but not the text set before it tries to draw and then gets stuck in a weird loop. The FT232H is noticeably slower at drawing than the Pi 4.

So the solution may be to not have displayio auto refresh on until it's all drawn out.

**Comment by makermelissa** [comment]
As an example. Here's the quotes running:
![301CD9E9-1D7C-45BF-9C52-C6D79C84286D_1_105_c](https://user-images.githubusercontent.com/2681417/86949183-264f1100-c103-11ea-9754-e24799ce5159.jpeg)

**Comment by caternuson** [comment]
OK, cool. Good test. The hardware seems fine then. So probably something software. Do you need help with this? I'm guessing this not something in the Blinka/FT232H layer of things. Probably more along the lines of what you're thinking above.

**Comment by makermelissa** [comment]
Thanks, I'll look into this more once I have my guide written. I'm making some changes to the PyPortal library and it'll be easier to just wait until those changes are in.

**Comment by makermelissa** [comment]
My changes are now in if you would like to take a look.

**Comment by caternuson** [comment]
How does this repo (PyPortal) come into play for the example in the original post above?

**Comment by makermelissa** [comment]
Oh right, here's the quotes example that I was running. You'll need to get the resources from https://github.com/adafruit/Adafruit_Learning_System_Guides/tree/master/PyPortal_Quotes

```
# SPDX-FileCopyrightText: 2017 Scott Shawcroft, written for Adafruit Industries
#
# SPDX-License-Identifier: Unlicense
"""
You can find any resources in the associated Learn Guide at:
https://learn.adafruit.com/pyportal-adafruit-quote-board
"""
import os
import time
from adafruit_pyportal import PyPortal

# Setup the Display
import board
import displayio
import adafruit_ili9341

displayio.release_displays()
spi = board.SPI()
tft_cs = board.D4
tft_dc = board.D5

display_bus = displayio.FourWire(
    spi, command=tft_dc, chip_select=tft_cs, reset=board.D6
)
display = adafruit_ili9341.ILI9341(display_bus, width=320, height=240)

# Set up where we'll be fetching data from
DATA_SOURCE = "https://www.adafruit.com/api/quotes.php"
QUOTE_LOCATION = [0, "text"]
AUTHOR_LOCATION = [0, "author"]

# the current working directory (where this file is)
try:
    cwd = os.path.dirname(os.path.realpath(__file__))
except AttributeError:
    cwd = ("/" + __file__).rsplit("/", 1)[0]

pyportal = PyPortal(
    display=display,
    debug=True,
    url=DATA_SOURCE,
    json_path=(QUOTE_LOCATION, AUTHOR_LOCATION),
    default_bg=cwd + "/quote_background.bmp",
    text_font=cwd + "/fonts/Arial-ItalicMT-17.bdf",
    text_position=((20, 120), (5, 210)),  # quote location  # author location
    text_color=(0xFFFFFF, 0x8080FF),  # quote text color  # author text color
    text_wrap=(35, 0),  # characters to wrap for quote  # no wrap for author
    text_maxlen=(180, 30),  # max text size for quote & author
)

# speed up projects with lots of text by preloading the font!
pyportal.preload_font()

while True:
    try:
        value = pyportal.fetch()
        print("Response is", value)
    except (ValueError, RuntimeError) as e:
        print("Some error occurred, retrying! -", e)
    time.sleep(60)
```

**Comment by makermelissa** [comment]
I noticed that the openweather example's time is not appearing on the Pi. It may or may not be related.

**Comment by makermelissa** [comment]
Using adafruit_display_text 2.7.5 seems to have fixed the openweather time not appearing issue. I wonder if this would fix this issue.

**Comment by caternuson** [comment]
How did you deal with neopixel support when running through the FT232H?

**Comment by makermelissa** [comment]
I'm just not using it. I can confirm that this is an issue with the Display Text library. Rolling back to version 2.7.5 fixed it.

**Comment by makermelissa** [comment]
Thanks for taking a look, but I'm going to close this since the issue isn't in this library. Issue https://github.com/adafruit/Adafruit_CircuitPython_Display_Text/issues/63 is now the issue and there's already a potential fix.

**Comment by caternuson** [comment]
OK, cool. If it starts looking like something FT232H related, feel free to ping me.

**Comment by makermelissa** [comment]
Thanks. Sounds good.
